# Packaging all.sh

_PHASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

run_logged "$_PHASE_DIR/00-essentials.sh"
run_logged "$_PHASE_DIR/fonts/all.sh"
run_logged "$_PHASE_DIR/terminal-emulators/all.sh"
run_logged "$_PHASE_DIR/runtimes/all.sh"
run_logged "$_PHASE_DIR/shells/all.sh"
run_logged "$_PHASE_DIR/audio/all.sh"
run_logged "$_PHASE_DIR/network/all.sh"
run_logged "$_PHASE_DIR/bluetooth/all.sh"
run_logged "$_PHASE_DIR/screenshots/all.sh"
run_logged "$_PHASE_DIR/clipboard/all.sh"
run_logged "$_PHASE_DIR/search-tools/all.sh"
run_logged "$_PHASE_DIR/file-tools/all.sh"
run_logged "$_PHASE_DIR/navigation-tools/all.sh"
run_logged "$_PHASE_DIR/git-tools/all.sh"
run_logged "$_PHASE_DIR/system-tools/all.sh"
run_logged "$_PHASE_DIR/data-tools/all.sh"
run_logged "$_PHASE_DIR/npm-globals/all.sh"
run_logged "$_PHASE_DIR/gh-extensions/all.sh"
run_logged "$_PHASE_DIR/agents/all.sh"
run_logged "$_PHASE_DIR/editors/all.sh"
run_logged "$_PHASE_DIR/ides/all.sh"
run_logged "$_PHASE_DIR/container-tools/all.sh"
run_logged "$_PHASE_DIR/25-dropbox.sh"
run_logged "$_PHASE_DIR/webbrowsers/all.sh"
run_logged "$_PHASE_DIR/40-keepassxc.sh"
run_logged "$_PHASE_DIR/55-pypr.sh"
run_logged "$_PHASE_DIR/api-tools/all.sh"
run_logged "$_PHASE_DIR/java-tools/all.sh"
run_logged "$_PHASE_DIR/database-tools/all.sh"
run_logged "$_PHASE_DIR/dev-tools/all.sh"
run_logged "$_PHASE_DIR/user-tools/all.sh"
run_logged "$_PHASE_DIR/gaming/all.sh"
