# Packaging all.sh

if [[ -z "${_GUARDS_LOADED:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "$SCRIPT_DIR/../helpers/all.sh"
fi

_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

run_logged "$_SELF_DIR/fonts/all.sh"
run_logged "$_SELF_DIR/terminal-emulators/all.sh"
run_logged "$_SELF_DIR/runtimes/all.sh"
run_logged "$_SELF_DIR/shells/all.sh"
run_logged "$_SELF_DIR/audio/all.sh"
run_logged "$_SELF_DIR/network/all.sh"
run_logged "$_SELF_DIR/bluetooth/all.sh"
run_logged "$_SELF_DIR/screenshots/all.sh"
run_logged "$_SELF_DIR/clipboard/all.sh"
run_logged "$_SELF_DIR/search-tools/all.sh"
run_logged "$_SELF_DIR/file-tools/all.sh"
run_logged "$_SELF_DIR/file-explorers/all.sh"
run_logged "$_SELF_DIR/navigation-tools/all.sh"
run_logged "$_SELF_DIR/vcs-tools/all.sh"
run_logged "$_SELF_DIR/system-tools/all.sh"
run_logged "$_SELF_DIR/data-tools/all.sh"
run_logged "$_SELF_DIR/npm-globals/all.sh"
run_logged "$_SELF_DIR/ia/all.sh"
run_logged "$_SELF_DIR/editors/all.sh"
run_logged "$_SELF_DIR/ides/all.sh"
run_logged "$_SELF_DIR/container-tools/all.sh"
run_logged "$_SELF_DIR/hyprland/all.sh"
run_logged "$_SELF_DIR/cloud-store/all.sh"
run_logged "$_SELF_DIR/webbrowsers/all.sh"
run_logged "$_SELF_DIR/secret-manager/all.sh"
run_logged "$_SELF_DIR/api-tools/all.sh"
run_logged "$_SELF_DIR/java-tools/all.sh"
run_logged "$_SELF_DIR/database-tools/all.sh"
run_logged "$_SELF_DIR/dev-tools/all.sh"
run_logged "$_SELF_DIR/user-tools/all.sh"
run_logged "$_SELF_DIR/gaming/all.sh"
