# Packaging all.sh

if [[ -z "${_GUARDS_LOADED:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "$SCRIPT_DIR/../helpers/all.sh"
fi

_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

run_logged "$_SELF_DIR/fonts/all.sh"
run_logged "$_SELF_DIR/terminal-emulators/all.sh"
run_logged "$_SELF_DIR/runtimes/all.sh"
run_logged "$_SELF_DIR/shells/all.sh"
run_logged "$_SELF_DIR/shell-plugins/all.sh"
run_logged "$_SELF_DIR/hardware/audio/all.sh"
run_logged "$_SELF_DIR/hardware/network/all.sh"
run_logged "$_SELF_DIR/hardware/bluetooth/all.sh"
run_logged "$_SELF_DIR/hardware/bottom.sh"
run_logged "$_SELF_DIR/hardware/hyperfine.sh"
run_logged "$_SELF_DIR/wayland/all.sh"
run_logged "$_SELF_DIR/search-tools/all.sh"
run_logged "$_SELF_DIR/file-explorers/all.sh"
run_logged "$_SELF_DIR/navigation-tools/all.sh"
run_logged "$_SELF_DIR/vcs-tools/all.sh"
run_logged "$_SELF_DIR/data-tools/all.sh"
run_logged "$_SELF_DIR/ia/all.sh"
run_logged "$_SELF_DIR/editors/all.sh"
run_logged "$_SELF_DIR/ides/all.sh"
run_logged "$_SELF_DIR/container-tools/all.sh"
run_logged "$_SELF_DIR/cloud-store/all.sh"
run_logged "$_SELF_DIR/web-browsers/all.sh"
run_logged "$_SELF_DIR/secret-managers/all.sh"
run_logged "$_SELF_DIR/api-tools/all.sh"
run_logged "$_SELF_DIR/database-tools/all.sh"
run_logged "$_SELF_DIR/dictation-tts/all.sh"
run_logged "$_SELF_DIR/screen-recording/all.sh"
run_logged "$_SELF_DIR/social/all.sh"
run_logged "$_SELF_DIR/dev-tools/all.sh"
run_logged "$_SELF_DIR/gaming/all.sh"
