#!/usr/bin/env sh

HYPRLAND_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.lua"
HYPRLAND_NO_SD_NOTIFY=1
HYPRLAND_NO_SD_VARS=1

export HYPRLAND_CONFIG HYPRLAND_NO_SD_NOTIFY HYPRLAND_NO_SD_VARS
