local vars = require("hyprland.variables")
local state = require("hyprland.scripts.state")
local theme = vars.HYDE_THEME or os.getenv("HYDE_THEME") or ""

local metadata = {
    theme = theme,
    gtk_theme = vars.GTK_THEME,
    icon_theme = vars.ICON_THEME,
    color_scheme = vars.COLOR_SCHEME,
    cursor_theme = vars.CURSOR_THEME,
    cursor_size = vars.CURSOR_SIZE,
    font = vars.FONT,
    font_size = vars.FONT_SIZE,
    bar_font = vars.BAR_FONT,
    notification_font = vars.NOTIFICATION_FONT,
    menu_font = vars.MENU_FONT,
    document_font = vars.DOCUMENT_FONT,
    document_font_size = vars.DOCUMENT_FONT_SIZE,
    monospace_font = vars.MONOSPACE_FONT,
    monospace_font_size = vars.MONOSPACE_FONT_SIZE,
    font_antialiasing = vars.FONT_ANTIALIASING,
    font_hinting = vars.FONT_HINTING,
    button_layout = vars.BUTTON_LAYOUT,
    terminal = vars.TERMINAL,
    -- HyDE metadata compatibility. The actual lock flow is controlled by hyde-shell/lockscreen.sh.
    lockscreen = "hyprlock",
}

local function write_conf(path, data)
    local file = io.open(path, "w")
    if not file then
        return
    end

    file:write("# Generated by hyprland/finale.lua\n")
    file:write("# Manual edits are not visible until you run: hyprctl reload\n")
    file:write("hyde {\n")
    file:write("    theme=", data.theme, "\n")
    file:write("    gtk-theme=", data.gtk_theme, "\n")
    file:write("    icon-theme=", data.icon_theme, "\n")
    file:write("    color-scheme=", data.color_scheme, "\n")
    file:write("    cursor-theme=", data.cursor_theme, "\n")
    file:write("    cursor-size=", data.cursor_size, "\n")
    file:write("    font=", data.font, "\n")
    file:write("    font-size=", data.font_size, "\n")
    file:write("    bar-font=", data.bar_font, "\n")
    file:write("    notification-font=", data.notification_font, "\n")
    file:write("    menu-font=", data.menu_font, "\n")
    file:write("    document-font=", data.document_font, "\n")
    file:write("    document-font-size=", data.document_font_size, "\n")
    file:write("    monospace-font=", data.monospace_font, "\n")
    file:write("    monospace-font-size=", data.monospace_font_size, "\n")
    file:write("    font-antialiasing=", data.font_antialiasing, "\n")
    file:write("    font-hinting=", data.font_hinting, "\n")
    file:write("    button-layout=", data.button_layout, "\n")
    file:write("    terminal=", data.terminal, "\n")
    file:write("    lockscreen=", data.lockscreen, "\n")
    file:write("}\n")
    file:close()
end

state.ensure_generated_dir()
write_conf(state.generated("hyprland.finale.conf"), metadata)

return metadata
