local home = os.getenv("HOME") or ""
local config_home = os.getenv("XDG_CONFIG_HOME") or (home .. "/.config")
local state_home = os.getenv("XDG_STATE_HOME") or (home .. "/.local/state")

local M = {
    generated_dir = state_home .. "/hypr/generated",
    legacy_generated_dir = config_home .. "/hypr/autogenerated_files",
}

local function shell_quote(value)
    return "'" .. value:gsub("'", "'\\''") .. "'"
end

local function readable(path)
    local file = io.open(path, "r")
    if not file then
        return false
    end
    file:close()
    return true
end

function M.generated(name)
    return M.generated_dir .. "/" .. name
end

function M.legacy_generated(name)
    return M.legacy_generated_dir .. "/" .. name
end

function M.existing_generated(name)
    local path = M.generated(name)
    if readable(path) then
        return path
    end
    return M.legacy_generated(name)
end

function M.ensure_generated_dir()
    os.execute("mkdir -p " .. shell_quote(M.generated_dir))
end

return M
