#Modified by Testcontainers
#Sun Dec 14 22:28:02 CET 2025
docker.api.version=1.44
docker.client.strategy=org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy
testcontainers.reuse.enable=true
