-- Generated by theme.switch.sh // Read-only
-- Manual edits are not visible until you run: hyprctl reload
return {
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        layout = "dwindle",
        resize_on_border = true,
        active_border = { colors = { "rgba(eb6f92ff)", "rgba(c4a7e7ff)", }, angle = 45 },
        inactive_border = { colors = { "rgba(31748fcc)", "rgba(9ccfd8cc)", }, angle = 45 },
    },
    group = {
        col = {
            border_active = { colors = { "rgba(eb6f92ff)", "rgba(c4a7e7ff)", }, angle = 45 },
            border_inactive = { colors = { "rgba(31748fcc)", "rgba(9ccfd8cc)", }, angle = 45 },
            border_locked_active = { colors = { "rgba(eb6f92ff)", "rgba(c4a7e7ff)", }, angle = 45 },
            border_locked_inactive = { colors = { "rgba(31748fcc)", "rgba(9ccfd8cc)", }, angle = 45 },
        },
    },
    decoration = {
        rounding = 10,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            contrast = 2,
            noise = 0.08,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
        },
    },
}
