#!/usr/bin/env bash
[[ $HYDE_SHELL_INIT -ne 1 ]] && eval "$(hyde-shell init)"
if [[ ${WALLBASH_STARTUP:-0} -eq 1 ]]; then
    exit 0
fi

# wallbash.conf is eliminated. Theme variables come from startup_vars.lua (written by theme.switch.sh).
# colors.conf is generated by the wallbash template pipeline (hyprcolors.dcol).
# When wallbash mode is active, regenerate hyprland.theme.lua with wallpaper-derived borders.

hypr_generated_dir="${HYPR_GENERATED_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}"
mkdir -p "$hypr_generated_dir"

if [[ ${PALETTE_SOURCE:-theme} != "theme" ]]; then
    tmp_colors="$(mktemp)"
    for i in 1 2 3 4; do
        pry_var="dcol_pry$i"
        txt_var="dcol_txt$i"
        printf 'wallbash_pry%s=%s\n' "$i" "${!pry_var:-}" >> "$tmp_colors"
        printf 'wallbash_txt%s=%s\n' "$i" "${!txt_var:-}" >> "$tmp_colors"
        for j in {1..9}; do
            xa_var="dcol_${i}xa${j}"
            printf 'wallbash_%sxa%s=%s\n' "$i" "$j" "${!xa_var:-}" >> "$tmp_colors"
        done
    done

    source "$LIB_DIR/hyde/lib/generate-hyprland-theme.sh"
    if [ -r "$HYDE_THEME_DIR/hypr.theme" ]; then
        generate_hyprland_lua_theme "$HYDE_THEME_DIR/hypr.theme" \
            "$hypr_generated_dir/hyprland.theme.lua" \
            --borders wallbash \
            --colors-file "$tmp_colors"
    else
        print_log -sec "wallbash" -warn "fallback" "HYDE_THEME_DIR/hypr.theme not readable; borders unchanged"
    fi
    rm -f "$tmp_colors"
fi
