[pyprland]
plugins = ["scratchpads"]

[pyprland.variables]
term_with_class = "kitty --class"

[scratchpads.console]
animation = "fromTop"
class = "console-dropdown"
command = "env NO_GREETING=1 xdg-terminal-exec --app-id=console-dropdown --title=console-dropdown"
size = "600px 150px"
margin = 180

[scratchpads.lazygit]
animation = "fromTop"
class = "pypr-lazygit"
command = "pypr-lazygit-cwd"
size = "80% 80%"
lazy = true
close_on_hide = true

[scratchpads.lazydocker]
animation = "fromTop"
class = "pypr-lazydocker"
command = "kitty --class pypr-lazydocker -e /home/linuxbrew/.linuxbrew/bin/lazydocker"
size = "80% 80%"
lazy = true

[scratchpads.ai-assistant]
animation = "fromTop"
class = "firefox"
command = "pypr-ai-assistant"
size = "55% 75%"
lazy = true
match_by = "class"
multi = false
process_tracking = false
