--? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

local function load(module)
    package.loaded[module] = nil
    return require(module)
end

-- HyDE compatibility and owned baseline config
load("hyprland.primary_apps") -- primary terminal, editor, file manager and browser
load("hyprland.variables")   -- HyDE variables table (scrPath, envList, unit, cursor, fonts, etc.)
load("hyprland.env")         -- hl.env(): Qt, Mozilla, Electron, XDG, PATH
load("hyprland.hardware.nvidia")  -- Nvidia env and cursor settings
load("hyprland.style.opacity") -- baseline opacity and dimming
load("hyprland.layout")      -- layout defaults: dwindle, master, snap
load("hyprland.hardware.input")   -- keyboard, mouse, touchpad
load("hyprland.misc")        -- misc compositor defaults
load("hyprland.hardware.gestures") -- touchpad gesture defaults
load("hyprland.dynamic")     -- screen shader, font family, mkdir, keybinds hint
load("hyprland.startup")     -- hl.on("hyprland.start"): dbus, polkit, bar, wallpaper, clipboard, applets, idle
load("hyprland.style.wallbash") -- wallbash metadata from autogenerated_files/wallbash.conf

-- User personal configuration
load("hyprland.hardware.monitors") -- monitor setup
load("hyprland.style.theme")      -- wallbash: autogenerated theme/colors parsing
load("hyprland.style.animations") -- animation curves from HYPR_ANIMATION state
load("hyprland.style.shaders")    -- screen shader from autogenerated_files/shaders.conf
load("hyprland.windowrules")      -- window rules
load("hyprland.style.windowrules") -- style-specific window rules
load("workflows")                 -- HyDE workflow overrides from HYPR_WORKFLOW state
load("hyprland.keybindings")      -- keyboard shortcuts

load("hyprland.finale")           -- HyDE metadata snapshot for tooling

hl.on("hyprland.start", function()
    hl.exec_cmd("pypr")
end)
