# ============================================================
#  Overrides master entry point
#  Add your custom overrides in the corresponding *.overrides.conf
#  These are sourced AFTER all HyDE defaults.
# ============================================================

source = ./keybindings.overrides.conf   # Keyboard shortcuts
source = ./windowrules.overrides.conf  # Window rules overrides
