#!/bin/sh
#
# Bootstrap script for setting up a new linux machine
#
# This should be idempotent so it can be run multiple times.
#

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
~/.local/bin/yadm submodule update --recursive --init

# Verify that Linuxbrew is installed
if ! command -v brew &> /dev/null
then
    echo 'brew must be installed! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")'   
else
    echo "Homebrew already installed. Getting updates and health..."
    brew update
    brew doctor
fi

echo ">>> Installing brew packages.."
brew bundle install --file ~/Brewfile

# sdkman
curl -s "https://get.sdkman.io?rcupdate=false" | bash

# link tabby config
#ln -s ~/.config/tabby/config.yaml ~/Library/Application\ Support/tabby/config.yaml

echo "Installing ZSH..."
sudo apt-get install zsh
chsh -s $(which zsh)

# done
echo "Bootstrapping complete"