#!/usr/bin/env zsh

for file in "${ZDOTDIR:-$HOME/.config/zsh}/conf.d/"*.zsh; do
  [[ ${file:t} == local.zsh ]] && continue
  [[ -r "$file" ]] && source "$file"
done

[[ -r "${ZDOTDIR:-$HOME/.config/zsh}/conf.d/local.zsh" ]] && source "${ZDOTDIR:-$HOME/.config/zsh}/conf.d/local.zsh"
