# Shell plugins all.sh

if [[ -z "${_GUARDS_LOADED:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "$SCRIPT_DIR/../../helpers/all.sh"
fi

_PHASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

run_logged "$_PHASE_DIR/starship.sh"
run_logged "$_PHASE_DIR/cava.sh"
run_logged "$_PHASE_DIR/pokego.sh"
run_logged "$_PHASE_DIR/gum.sh"
run_logged "$_PHASE_DIR/fastfetch.sh"
run_logged "$_PHASE_DIR/bash-completion.sh"
run_logged "$_PHASE_DIR/bat.sh"
run_logged "$_PHASE_DIR/eza.sh"
run_logged "$_PHASE_DIR/duf.sh"
run_logged "$_PHASE_DIR/expac.sh"
run_logged "$_PHASE_DIR/tealdeer.sh"
run_logged "$_PHASE_DIR/fisher-package.sh"
run_logged "$_PHASE_DIR/fish-pure-prompt.sh"
run_logged "$_PHASE_DIR/fish-autopair.sh"
run_logged "$_PHASE_DIR/zsh/all.sh"
run_logged "$_PHASE_DIR/gotty.sh"
run_logged "$_PHASE_DIR/snip.sh"
run_logged "$_PHASE_DIR/sl.sh"
run_logged "$_PHASE_DIR/cmatrix.sh"
run_logged "$_PHASE_DIR/cowsay.sh"
run_logged "$_PHASE_DIR/fortune-mod.sh"
run_logged "$_PHASE_DIR/figlet.sh"
run_logged "$_PHASE_DIR/toilet.sh"
run_logged "$_PHASE_DIR/lolcat.sh"
run_logged "$_PHASE_DIR/asciiquarium.sh"
run_logged "$_PHASE_DIR/nyancat.sh"
run_logged "$_PHASE_DIR/pipes.sh"
run_logged "$_PHASE_DIR/cbonsai.sh"
run_logged "$_PHASE_DIR/ponysay.sh"
run_logged "$_PHASE_DIR/hollywood.sh"
run_logged "$_PHASE_DIR/clocktemp.sh"
run_logged "$_PHASE_DIR/fzf-fish.sh"
run_logged "$_PHASE_DIR/aalib.sh"
